name: 'Build Image To AliCloud Container Registry'
description: 'Build Image To AliCloud Container Registry'
inputs:
  access-key-id:
    description: 'AliCloud Access Key'
    required: false
    default: ''
  access-key-secret:
    description: 'AliCloud Secret Key'
    required: false
    default: ''
  region-id:
    description: 'AliCloud Region Id'
    required: false
    default: 'cn-hongkong'
  sae-config-map-id:
    description: 'SAE ConfigMap ID'
    required: false
    default: ''
  env_vars:
    description: "List of environment variables to pass to Docker build"
    required: false
  final_image_url:
    description: "Final Docker image URL including tag"
    required: true

branding:
  color: 'green'
  icon: 'anchor'

runs:
  using: composite
  steps:
    # 使用 SAE 配置项 ID 获取配置项
    - name: Node.js environment setup
      if: ${{ inputs.sae-config-map-id != '' }}
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Load SAE ConfigMap
      if: ${{ inputs.sae-config-map-id != '' }}
      run: node index.js
      shell: bash

    # 编译并提交镜像到ACR
    - name: Build and Push Docker Image To ACR
      shell: bash
      env:
        FINAL_IMAGE_URL: ${{ inputs.final_image_url }}
      run: entrypoint.sh

