name: 'Build Image To AliCloud Container Registry'
description: 'Build Image To AliCloud Container Registry'
inputs:
  access-key-id:
    description: 'AliCloud Access Key'
    required: true
    default: ''
  access-key-secret:
    description: 'AliCloud Secret Key'
    required: true
    default: ''
  region-id:
    description: 'AliCloud Region Id'
    required: true
    default: ''
  sae-app-id:
    description: 'SAE Application ID'
    required: true
    default: ''
  acr-image-url:
    description: 'ACR Docker Image URL'
    required: true
    default: ''
  acr-instance-id:
    description: 'ACR Instance ID'
    required: true
    default: ''
branding:
  color: 'green'
  icon: 'anchor'
runs:
  using: 'node20'
  main: 'dist/index.js'
