name: 'Send Github Action Notification To Lark With Webhook'
description: 'Send Github Action Notification To Lark With Webhook'
author: 'Felix Liu'
inputs:
  webhook:
    description: 'Lark Bot Webhook'
    required: true
    default: ''
  icon:
    description: 'Lark Message Icon Id'
    required: false
    default: 'img_v3_02dv_55b29871-b41f-42ed-bbcd-7e90834cb6hu'
  project-url:
    description: 'Project Url'
    required: true
    default: ''
  status:
    description: 'Action Build Status'
    required: true
    default: ''
  title:
    description: 'Notification Title'
    required: true
    default: ''
  message:
    description: 'Notification Message'
    required: true
    default: ''
  alert-members:
    description: 'Alert Lark Member Ids'
    required: false
    default: ''
  trigger:
    description: 'Action Trigger Username'
    required: true
    default: ''
  timestamp:
    description: 'Trigger Date Timestamp'
    required: true
    default: ''
  duration:
    description: 'Action Run Duration'
    required: true
    default: ''
  changes:
    description: 'Changes Detail'
    required: true
    default: ''
  log-url:
    description: 'Logs Url'
    required: false
    default: ''

branding:
  color: 'green'
  icon: 'anchor'

runs:
  using: 'node20'
  main: 'dist/index.js'
