name: 'Send Github Action Notification To Lark With Webhook'
description: 'Send Github Action Notification To Lark With Webhook'
author: 'Felix Liu'
inputs:
  webhook:
    description: 'Lark Bot Webhook'
    required: true
    default: ''
  icon:
    description: 'Lark Message Icon Id'
    required: false
    default: 'img_v3_02dv_55b29871-b41f-42ed-bbcd-7e90834cb6hu'
  environment:
    description: 'Build Environment'
    required: true
    default: ''
  status:
    description: 'Action Build Status'
    required: true
    default: ''
  title:
    description: 'Notification Title'
    required: true
    default: ''
  repository:
    description: 'Repository Name'
    required: true
    default: ''
  alert-members:
    description: 'Alert Lark Member Ids'
    required: false
    default: ''
  trigger:
    description: 'Action Trigger Username'
    required: true
    default: ''
  start-time:
    description: 'Action Run Start Time (Seconds)'
    required: true
    default: '0'
  end-time:
    description: 'Action Run End Time (Seconds)'
    required: true
    default: '0'
  run-id:
    description: 'Action Run Id'
    required: true
    default: ''

branding:
  color: 'green'
  icon: 'anchor'

runs:
  using: 'node20'
  main: 'dist/index.js'
