name: "Docker Build with SAE ConfigMap"
description: "Build Docker image with environment variables and push to registry"
inputs:
  env_vars:
    description: "List of environment variables to pass to Docker build"
    required: false
  final_image_url:
    description: "Final Docker image URL including tag"
    required: true
runs:
  using: docker
  image: docker:20.10.7
  entrypoint: entrypoint.sh